CREATE DATABASE IF NOT EXISTS pasien_db;
USE pasien_db;

-- Create Patient Table
CREATE TABLE IF NOT EXISTS datapasien (
    Patient_ID VARCHAR(10) PRIMARY KEY,
    Full_Name VARCHAR(100) NOT NULL,
    Gender ENUM('Male', 'Female') NOT NULL,
    Age INT NOT NULL,
    Diagnosis VARCHAR(100) NOT NULL
    );

-- Insert 50 data dummy
INSERT INTO datapasien (Patient_ID, Full_Name, Gender, Age, Diagnosis) VALUES
('P001', 'Ahmad Wijaya', 'Male', 8, 'Fever'),
('P002', 'Siti Rahayu', 'Female', 15, 'Colds'),
('P003', 'Budi Santoso', 'Male', 5, 'Diarrhea'),
('P004', 'Dewi Lestari', 'Female', 12, 'Chickenpox'),
('P005', 'Rizki Pratama', 'Male', 18, 'Fever'),
('P006', 'Maya Sari', 'Female', 3, 'Colds'),
('P007', 'Fajar Abdullah', 'Male', 10, 'Diarrhea'),
('P008', 'Nina Kamila', 'Female', 7, 'Chickenpox'),
('P009', 'Hendra Gunawan', 'Male', 16, 'Fever'),
('P010', 'Lia Amelia', 'Female', 14, 'Colds'),
('P011', 'Agus Setiawan', 'Male', 35, 'Tuberculosis'),
('P012', 'Rina Marlina', 'Female', 28, 'Diabetes'),
('P013', 'Joko Susilo', 'Male', 42, 'High Blood Pressure'),
('P014', 'Sari Indah', 'Female', 31, 'Tuberculosis'),
('P015', 'Dimas Prayoga', 'Male', 45, 'Diabetes'),
('P016', 'Fitri Handayani', 'Female', 38, 'High Blood Pressure'),
('P017', 'Ari Wibowo', 'Male', 29, 'Tuberculosis'),
('P018', 'Diana Putri', 'Female', 33, 'Diabetes'),
('P019', 'Eko Prasetyo', 'Male', 47, 'High Blood Pressure'),
('P020', 'Mira Utami', 'Female', 26, 'Tuberculosis'),
('P021', 'Rudi Hermawan', 'Male', 39, 'Diabetes'),
('P022', 'Yuni Astuti', 'Female', 44, 'High Blood Pressure'),
('P023', 'Firman Syah', 'Male', 32, 'Tuberculosis'),
('P024', 'Tuti Alawiyah', 'Female', 41, 'Diabetes'),
('P025', 'Hadi Nugroho', 'Male', 36, 'High Blood Pressure'),
('P026', 'Surya Dinata', 'Male', 67, 'Cancer'),
('P027', 'Murni Wati', 'Female', 72, 'Heart Diseases'),
('P028', 'Tono Saputra', 'Male', 58, 'Alzheimer'),
('P029', 'Sri Rejeki', 'Female', 65, 'Dementia'),
('P030', 'Bambang Umar', 'Male', 81, 'Cancer'),
('P031', 'Endah Sulistyo', 'Female', 76, 'Heart Diseases'),
('P032', 'Jaya Makmur', 'Male', 63, 'Alzheimer'),
('P033', 'Kartini Dewi', 'Female', 69, 'Dementia'),
('P034', 'Lukman Hakim', 'Male', 85, 'Cancer'),
('P035', 'Ningsih Ratna', 'Female', 71, 'Heart Diseases'),
('P036', 'Oscar Fernando', 'Male', 59, 'Alzheimer'),
('P037', 'Putri Ayu', 'Female', 66, 'Dementia'),
('P038', 'Rahmat Hidayat', 'Male', 78, 'Cancer'),
('P039', 'Siska Wulandari', 'Female', 74, 'Heart Diseases'),
('P040', 'Teguh Prakoso', 'Male', 62, 'Alzheimer'),
('P041', 'Wati Sumarni', 'Female', 68, 'Dementia'),
('P042', 'Yusuf Mansur', 'Male', 83, 'Cancer'),
('P043', 'Zahra Fadilah', 'Female', 77, 'Heart Diseases'),
('P044', 'Adi Sutrisno', 'Male', 61, 'Alzheimer'),
('P045', 'Citra Permata', 'Female', 64, 'Dementia'),
('P046', 'Guntur Eka', 'Male', 79, 'Cancer'),
('P047', 'Intan Purnama', 'Female', 75, 'Heart Diseases'),
('P048', 'Kurniawan Adi', 'Male', 60, 'Alzheimer'),
('P049', 'Lestari Ningrum', 'Female', 70, 'Dementia'),
('P050', 'Mulyadi Jaya', 'Male', 82, 'Cancer');